//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quan_ly_ban_hang
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int IDTK { get; set; }
        public string DisplayName { get; set; }
        public string UserName { get; set; }
        public string PASSWORD { get; set; }
        public int Department { get; set; }
    }
}
