//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quan_ly_ban_hang
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietDonHang()
        {
            this.DonDatHangs = new HashSet<DonDatHang>();
            this.DonHang_Muc = new HashSet<DonHang_Muc>();
        }
    
        public int IDDetail { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> IDSale { get; set; }
        public Nullable<int> IDFood { get; set; }
    
        public virtual FOOD FOOD { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatHang> DonDatHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang_Muc> DonHang_Muc { get; set; }
    }
}
