//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quan_ly_ban_hang
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang
    {
        public int IDOrder { get; set; }
        public System.TimeSpan Time { get; set; }
        public string StatusOrder { get; set; }
        public Nullable<int> IDNV { get; set; }
        public Nullable<int> IDKH { get; set; }
        public Nullable<int> IDDetail { get; set; }
    
        public virtual ChiTietDonHang ChiTietDonHang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual ThongTinNV ThongTinNV { get; set; }
    }
}
