CREATE DATABASE QLYcuahang
ON PRIMARY
    (NAME = QLBanHang_data,
    FILENAME = 'C:\Users\vienc\Desktop\SQL\QLBanHang.mdf',
    SIZE = 10MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 5MB )
LOG ON
    (NAME = QLBanHang_log,
    FILENAME = 'C:\Users\vienc\Desktop\SQL\QLBanHang.ldf',
    SIZE = 5MB,
    MAXSIZE = 100MB,
    FILEGROWTH = 5MB);

GO
USE QLYcuahang

GO
CREATE TABLE NhanVien (
    MaNV INT PRIMARY KEY,
    TenNV VARCHAR(255) NOT NULL,
    SDT VARCHAR(15) NOT NULL,
    Email VARCHAR(255) NOT NULL,
);

CREATE TABLE KhuyenMai (
    MaKM INT PRIMARY KEY,
    LoaiKM VARCHAR(255) NOT NULL,
    NgayBatDau DATE NOT NULL,
    NgayKetThuc DATE NOT NULL,
    ComboKM VARCHAR(255),
    PhanTramGiam FLOAT NOT NULL
);

CREATE TABLE ThanhVien (
    SDTTV VARCHAR(15) PRIMARY KEY,
    TenTV VARCHAR(255) NOT NULL,
    Email VARCHAR(255)
);

CREATE TABLE SanPham (
    MaSP INT PRIMARY KEY,
    TenSP VARCHAR(255) NOT NULL,
    Gia FLOAT NOT NULL,
    SoLuong INT NOT NULL
);

CREATE TABLE HoaDon (
    MaHD INT PRIMARY KEY,
    NgayTao DATE NOT NULL,
    SDT VARCHAR(15) NOT NULL,
    MaNV INT NOT NULL,
    MaKM INT,
    FOREIGN KEY (SDT) REFERENCES ThanhVien(SDTTV),
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
    FOREIGN KEY (MaKM) REFERENCES KhuyenMai(MaKM)
);

CREATE TABLE CTHD (
    MaHD INT NOT NULL,
    MaSP INT NOT NULL,
    SL INT NOT NULL,
    DonGia FLOAT NOT NULL,
    TongTien FLOAT NOT NULL,
    PRIMARY KEY (MaHD, MaSP),
    FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD),
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);
